### ISSUE TITLE
add UserDataDir

### ISSUE THREAD

**Issue by dmitry200** [gshev/playwright-extra-sharp#1]
hi, classic chromium.launchPersistent supports userDataDir, can you update your PlaywrightExtra.LaunchAsync and add userDataDir?

**Comment by gshev** [comment]
Hi. Yeah, already did :)
Just need to clean up and test it before upload.
Unfortunately, playwright is being jerk and not cleaning resources when context persistent between requests.
If you make like several thousands requests per context lifetime, you'd get massive memory leaks.
So i've left choice to user. Now you'll be able to run it with following scenarios:
1. launch incognito (as default was) with permanent context
2. launch incognito with new context per page (so when page is closed, context is disposed)
3. launch persistent (user data dir is considered) with permanent context
4. launch persistent with new context per page
