### ISSUE TITLE
Duplicate Content Items error

### ISSUE THREAD

**Issue by strich** [gshev/playwright-extra-sharp#3]
I tried adding this lib to our MAUI Blazor app and got the following error:

`Error	NETSDK1022	Duplicate 'Content' items were included. The .NET SDK includes 'Content' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultContentItems' property to 'false' if you want to explicitly include them in your project file. For more information, see https://aka.ms/sdkimplicititems. The duplicate items were: 'C:\Users\user\.nuget\packages\microsoft.playwright\1.38.0\buildTransitive\..\.playwright\node\LICENSE'	C:\Program Files\dotnet\sdk\7.0.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.Shared.targets	213		Normal`

**Comment by gshev** [comment]
Not sure how is it related to extra library.
Error points to core playwright itself. And by error message, i can just presume that you have conflict LICENSE file.
Maybe try to clean nuget cache and reinstall, other than that, i dont think i can help you with that, sorry.
